### ISSUE TITLE
investigate featuretools

### ISSUE THREAD

**Issue by cdleong** [cdleong/pyfantasy#16]
Here's an example of using featuretools for hockey: https://towardsdatascience.com/automated-feature-engineering-for-predictive-modeling-d8c9fa4e478b

Can we use this in this project?

**Comment by kmax12** [comment]
hi @cdleong I am one of the developers of Featuretools. if you choose to use it, we're happy to help. good luck!

**Comment by cdleong** [comment]
Thank you! I'm definitely interested in checking it out at least. Appreciate it.
