### ISSUE TITLE
Graph the player data

### ISSUE THREAD

**Issue by cdleong** [cdleong/pyfantasy#18]
Do some exploration of the Player data. 

Examples: sort the wide receivers by score, then figure out the distribution. 

Sounds like a good job for Pandas and Seaborn...

**Comment by ColinLeongUDRI** [comment]
Figured out how to get the actual fantasy scores from the league. 

Converted that to Pandas Dataframe, 

Then made a Seaborn distplot:
![qb_top_14](https://user-images.githubusercontent.com/46969615/51656616-d3fe4c80-1f6f-11e9-8eb8-ed3f4b3ae9af.png)
![rb](https://user-images.githubusercontent.com/46969615/51656617-d3fe4c80-1f6f-11e9-8f86-54aa0610a681.png)
![rb_top_14](https://user-images.githubusercontent.com/46969615/51656618-d3fe4c80-1f6f-11e9-92cb-849265d96f69.png)
![te](https://user-images.githubusercontent.com/46969615/51656620-d3fe4c80-1f6f-11e9-8383-15f1fe334b2d.png)
![te_top_14](https://user-images.githubusercontent.com/46969615/51656621-d496e300-1f6f-11e9-87fe-d69d5c932ee3.png)
![wr](https://user-images.githubusercontent.com/46969615/51656622-d496e300-1f6f-11e9-9e04-692784606154.png)
![wr_top_14](https://user-images.githubusercontent.com/46969615/51656623-d496e300-1f6f-11e9-8f65-9c6b7d9b28aa.png)
![def](https://user-images.githubusercontent.com/46969615/51656624-d496e300-1f6f-11e9-8f8a-46b45a6221a3.png)
![def_top_14](https://user-images.githubusercontent.com/46969615/51656626-d496e300-1f6f-11e9-90f9-7b96de9cddd8.png)
![k](https://user-images.githubusercontent.com/46969615/51656627-d496e300-1f6f-11e9-8cc5-79d4e002df93.png)
![k_top_14](https://user-images.githubusercontent.com/46969615/51656628-d496e300-1f6f-11e9-9a37-3b4ef2d28a48.png)
![qb](https://user-images.githubusercontent.com/46969615/51656629-d496e300-1f6f-11e9-9e03-1749d804c654.png)

**Comment by ColinLeongUDRI** [comment]
![qb](https://user-images.githubusercontent.com/46969615/51656725-44a56900-1f70-11e9-92aa-ea3c869b7f64.png)
![qb_top_14](https://user-images.githubusercontent.com/46969615/51656727-44a56900-1f70-11e9-8b27-d9d8ae461f02.png)
![rb](https://user-images.githubusercontent.com/46969615/51656728-44a56900-1f70-11e9-9765-df9f6e171eaf.png)
![rb_top_14](https://user-images.githubusercontent.com/46969615/51656729-44a56900-1f70-11e9-8866-aaa2a07da51d.png)
![te](https://user-images.githubusercontent.com/46969615/51656730-44a56900-1f70-11e9-86a2-7e1dc406eba4.png)
![te_top_14](https://user-images.githubusercontent.com/46969615/51656731-44a56900-1f70-11e9-845f-4334cbe49ffd.png)
![wr](https://user-images.githubusercontent.com/46969615/51656733-453dff80-1f70-11e9-85c1-41eb479a20d4.png)
![wr_top_14](https://user-images.githubusercontent.com/46969615/51656734-453dff80-1f70-11e9-9890-4810c4c47c53.png)
![def](https://user-images.githubusercontent.com/46969615/51656735-453dff80-1f70-11e9-8239-9080b0747d1d.png)
![def_top_14](https://user-images.githubusercontent.com/46969615/51656736-453dff80-1f70-11e9-9965-05ad7feff5f4.png)
![k](https://user-images.githubusercontent.com/46969615/51656737-453dff80-1f70-11e9-9bc3-130544962f3d.png)
![k_top_14](https://user-images.githubusercontent.com/46969615/51656738-453dff80-1f70-11e9-9eb4-ff010fbb0266.png)

Now with titles!

**Comment by cdleong** [comment]
Figured out how to query for the actual data from my work league, which gave me actual fantasy points scored. 

Then looped through that, and made a Pandas dataframe, 

Then passed that to a Seaborn distplot, and got this: 

![k_top_14](https://user-images.githubusercontent.com/4109253/51656840-8f26e580-1f70-11e9-8b55-69276ba27fc4.png)
![qb](https://user-images.githubusercontent.com/4109253/51656841-8fbf7c00-1f70-11e9-9085-37c6f09c4bbd.png)
![qb_top_14](https://user-images.githubusercontent.com/4109253/51656842-8fbf7c00-1f70-11e9-90eb-f21f169d001a.png)
![rb](https://user-images.githubusercontent.com/4109253/51656843-8fbf7c00-1f70-11e9-95ad-5f34e8ccafeb.png)
![rb_top_14](https://user-images.githubusercontent.com/4109253/51656844-8fbf7c00-1f70-11e9-9415-2334cab9504d.png)
![te](https://user-images.githubusercontent.com/4109253/51656845-8fbf7c00-1f70-11e9-8625-c419796071ab.png)
![te_top_14](https://user-images.githubusercontent.com/4109253/51656847-8fbf7c00-1f70-11e9-89bf-68ab38a6bf96.png)
![wr](https://user-images.githubusercontent.com/4109253/51656848-8fbf7c00-1f70-11e9-8de8-61f5bb8dd1db.png)
![wr_top_14](https://user-images.githubusercontent.com/4109253/51656849-90581280-1f70-11e9-8197-ce7d235322dc.png)
![def](https://user-images.githubusercontent.com/4109253/51656850-90581280-1f70-11e9-9810-a0364d76a0b1.png)
![def_top_14](https://user-images.githubusercontent.com/4109253/51656851-90581280-1f70-11e9-9409-49dd36bf10c4.png)
![k](https://user-images.githubusercontent.com/4109253/51656852-90581280-1f70-11e9-8b05-914f45e3b8d8.png)

**Comment by cdleong** [comment]
Note how Patrick Mahomes kinda jumps out as an outlier here: 

![qb_top_14](https://user-images.githubusercontent.com/4109253/51656938-cf866380-1f70-11e9-9e33-a77ced9a61ab.png)

**Comment by cdleong** [comment]
Boxplot!

Again, Mahomes is a clear outlier: 

![player_box](https://user-images.githubusercontent.com/4109253/51657483-1a08df80-1f73-11e9-9a0b-e3c84dc357fb.png)

**Comment by cdleong** [comment]
It has been pointed out to me, that in our league we had TWO wide receivers per team. So some positions have, shall we say, higher demand. Graphed the top 28 for each position now:

![te_top_28](https://user-images.githubusercontent.com/4109253/52138207-87270f80-261a-11e9-81f7-7c43e6d9b86d.png)
![qb_top_28](https://user-images.githubusercontent.com/4109253/52138208-87270f80-261a-11e9-9858-d4f3a3c6cc0c.png)
![k_top_28](https://user-images.githubusercontent.com/4109253/52138210-87270f80-261a-11e9-93c4-408f79aff2ac.png)
![def_top_28](https://user-images.githubusercontent.com/4109253/52138211-87270f80-261a-11e9-9d4c-5cd85419b176.png)
![rb_top_28](https://user-images.githubusercontent.com/4109253/52138212-87270f80-261a-11e9-9f22-885e49f23633.png)
![wr_top_28](https://user-images.githubusercontent.com/4109253/52138213-87270f80-261a-11e9-8e0d-21da260ce004.png)
