### ISSUE TITLE
Documentation: Process for auth-key generation for Yahoo API

### ISSUE THREAD

**Issue by FuzzyMcGraw** [cdleong/pyfantasy#19]
In trying to run the yahoo draft advisor, it requests login to the OAuth page, but I encounter an error page. Can you document how you generated your auth keys? 

*Player 2 has entered the game*

**Comment by cdleong** [comment]
Essentially, you have to make an app on the Yahoo Developer site.

Trying to recreate the steps: 
First, I think I made an app: https://developer.yahoo.com/apps/create/
![image](https://user-images.githubusercontent.com/4109253/53207958-36944800-3603-11e9-969c-8b8c830509e2.png)

![image](https://user-images.githubusercontent.com/4109253/53207995-4875eb00-3603-11e9-9004-821a2bf8e078.png)

I selected "installed application" and  "read/write permissions."

You then have access to the keys and such:

![image](https://user-images.githubusercontent.com/4109253/53208041-70654e80-3603-11e9-8859-a44c41e934d6.png)


You put those in the file "auth_keys.txt" in pyfantasy, like so: 

```
consumer_secret: 6d2ed90638f1c84a70fc51fd48da867967df3c9d
consumer_key: dj0yJmk9WElQREZjaVRhYUNXJnM9Y29uc3VtZXJzZWNyZXQmc3Y9MCZ4PWEx
```

More Fantasy API info: https://developer.yahoo.com/fantasysports/

**Comment by cdleong** [comment]
For Pyfantasy, the client ID is dj0yJmk9aG82MHR6TDM3YUhkJmQ9WVdrOVN6SnNZemRpTjJVbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD1hMg--

**Comment by cdleong** [comment]
I think this page also relevant: https://developer.yahoo.com/dsp/api/docs/authentication/enable-oauth.html

**Comment by cdleong** [comment]
And perhaps this: https://developer.yahoo.com/oauth2/guide/

**Comment by cdleong** [comment]
Actually, I guess I can just... include an auth_keys.txt in the repo, with the client_ID?

**Comment by cdleong** [comment]
https://github.com/thorrr/YahooSports README has more info

**Comment by cdleong** [comment]
Upon digging into it more, I think only the ID should be necessary, but the YahooSports repo requires both?

On this page, they only use the CLIENT_ID: https://developer.yahoo.com/dsp/api/docs/authentication/enable-oauth.html


https://api.login.yahoo.com/oauth2/request_auth?client_id=dj0yJmk9aG82MHR6TDM3YUhkJmQ9WVdrOVN6SnNZemRpTjJVbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD1hMg--&redirect_uri=oob&response_type=code&language=en-us

seems to work fine. No "secret" required.

**Comment by cdleong** [comment]
This page confirms you share the ID, but not the secret: https://www.oauth.com/oauth2-servers/client-registration/client-id-secret/

**Comment by FuzzyMcGraw** [comment]
Excellent. No need to include AuthKeys in the repo, probably shouldn't for safety reasons. Each user needs their own client_ID too, I think.
