### ISSUE TITLE
Idea: live twitter analysis to provide Player alerts?

### ISSUE THREAD

**Issue by cdleong** [cdleong/pyfantasy#25]
Idea: scrape twitter for, things like "Antonio Brown" and "IR". 

This link describes twitter-scraping: https://towardsdatascience.com/sentiment-analysis-of-anthem-game-launch-in-python-16be9e5083d2

**Comment by SpaceGhostForce** [comment]
Are you looking to do this on a certain platform? There's a GitHub for a discord bot that provides a lot of what you're looking for.
